sudo: required
dist: trusty
language: generic
install:
      - sudo add-apt-repository -y ppa:deadsnakes/ppa
      - sudo apt-get -qq update
      - sudo apt-get install -y python3.6 python3.6-dev python3.5 python-3.5-dev librocksdb-dev
      - sudo pip install -U pip tox
script:
      - tox
env:
      - TOXENV=py27
      - TOXENV=py36
      - TOXENV=docs
